language: node_js

node_js:
  - '12'

sudo: false

cache: yarn

script:
  - yarn run test:ci

after_success:
  - codecov

before_deploy:
  - yarn run build
  - cp ./build/index.html ./build/200.html

deploy:
  provider: surge
  project: ./build/
  domain: example.surge.sh
  skip_cleanup: true
